version: '3.8'

services:
  # MongoDB Database (No Auth - Development Only)
  mongodb:
    image: mongo:7.0
    container_name: greencart-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - greencart-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: greencart-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/greencart-logistics
      JWT_SECRET: development-jwt-secret
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - greencart-network
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const options = { host: 'localhost', port: 5000, path: '/api/health', timeout: 2000 }; const request = http.request(options, (res) => { process.exitCode = res.statusCode === 200 ? 0 : 1; }); request.on('error', function(err) { process.exitCode = 1; }); request.end();"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: greencart-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - greencart-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # MongoDB Express (No Auth Required)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: greencart-mongo-express-dev
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - greencart-network

networks:
  greencart-network:
    driver: bridge
    name: greencart-network-dev

volumes:
  mongodb_data:
    driver: local
    name: greencart-mongodb-data-dev
